[application]
name = "jpass"
default_platform = "desktop"

[bundle]
identifier = "dev.jpass.app"

[web.app]
title = "JPass"

[web.watcher]
watch_path = ["src", "assets"]

[web.resource]
style = ["assets/main.css"]

[web.resource.dev]
